version: "3.9"
services:
  web:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: development
    ports:
      - "8000:8000"
    command: sh -c "pip install -r requirements.txt && python wsgi.py"
